// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lgvoikshvvrcrixvggpf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxndm9pa3NodnZyY3JpeHZnZ3BmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMzc1MTMsImV4cCI6MjA1OTgxMzUxM30.bUqTqi0uV2xOzDmLmtz19XeQvqe9e84yo-TlDmZ8J_8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);